DROP SCHEMA IF EXISTS CICLISMO_BBDD ;
CREATE SCHEMA IF NOT EXISTS  CICLISMO_BBDD ; 
USE CICLISMO_BBDD ; 

CREATE TABLE CARRERA (
ID_CARRERA INT ,
NOMBRE VARCHAR(20),
LONGITUD INT,
DURACION INT,
LOCACION VARCHAR(15),
PRIMARY KEY(ID_CARRRERA)
); 

CREATE TABLE COMPETIDORES (
ID_COMPETIDOR INT ,
NOMBRE VARCHAR(15),
APELLIDO VARCHAR (15),
EDAD INT (2),
NACIONALIDAD VARCHAR (10),
EQUIPO VARCHAR (15),
CANTIDAD_CARRERAS INT (3),
PRIMARY KEY (ID_COMPETIDOR),
FOREIGN KEY (ID_CARRERAS) REFERENCES CARRERAS(ID_CARRERAS)
);


CREATE TABLE EQUIPOS (
ID_EQUIPO INT,
NOMBRE INTEGER,
MIEMBROS INT,
CARRERAS_CONCURSADAS INT, 
PAIS INTEGER,
CARRERAS_GANADAS INT,
ID_MARCA INT,
PRIMARY KEY (ID_EQUIPO),
FOREIGN KEY (ID_MARCA) REFERENCES BICICLETAS(ID_MARCA)
);


CREATE TABLE BICICLETAS (
ID_MARCA INT, 
MODELO INTEGER,
TIPO INTEGER, 
PAIS INTEGER,
ID_EQUIPO INT,
PRIMARY KEY (ID_MARCA),
FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS(ID_EQUPOS)
);

CREATE TABLE INFORMACION_HISTORICA (
ID_CARRERA INT, 
AÑO_CARRERA INT, 
EQUIPO_ID INT, 
GANADORES INT,
RECOR_VELOCIDAD INT,
FOREIGN KEY (ID_CARRERA, EQUIPO_ID) REFERENCES EQUIPOS(ID_EQUPOS)
);

